# Generated by Django 4.2.5 on 2023-09-18 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charity_hub', '0005_remove_userprofile_image_charity_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_number', models.CharField(editable=False, max_length=30)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=40)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('town_or_city', models.CharField(max_length=40)),
                ('street_address1', models.CharField(max_length=80)),
                ('street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('county', models.CharField(blank=True, max_length=80, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='donation_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('charity_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity_hub.charity')),
                ('donation_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='payment.donation_payment')),
            ],
        ),
    ]
