# Generated by Django 4.2.5 on 2023-09-17 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_hub', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charity',
            options={'verbose_name_plural': 'charities'},
        ),
    ]
