# Generated by Django 4.2.5 on 2023-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_hub', '0003_alter_charity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='charity_images/'),
        ),
    ]
